---
- name: "Building Docker Image From Grihub Repository"
  hosts: build
  become: true
  vars_files:
    - docker-credentials.yml
  vars:
    packages:
      - git
      - pip
      - docker
    project_repo_url: "https://github.com/AryaSathyan/devops-flask.git"
    clone_dir: "/var/flask_app/"
    image_name: "aryasathyan/oncompute"
        
  tasks:
                  
    - name: "Build - Installing packages"
      yum:
        name: "{{ packages }}"
        state: present
    
    - name: "Build - Adding Ec2-user to docker group"
      user:
        name: "ec2-user"
        groups:
          - docker
        append: true
            
            
    - name: "Build - Installing Python Extension For Docker"
      pip:
        name: docker-py
            
    - name: "Build - Restarting/Enabling Docker Service"
      service:
        name: docker
        state: restarted
        enabled: true
            
    - name: "Build - Clonning Repo {{ project_repo_url }}"
      git:
        repo: "{{project_repo_url}}"
        dest: "{{ clone_dir }}"
      register: clone_status
        
    - debug:
        var: clone_status
            
            
    - name: "Build - Loging to Docker-hub Account"
      when: clone_status.changed == true
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
        state: present
    
    
    - name: "Build - Creating Docker Image And Push To Docker-hub"
      when: clone_status.changed == true
      docker_image:
        source: build
        build:
          path: "{{ clone_dir }}"
          pull: yes
        name: "{{ image_name }}"
        tag: "{{ item }}"
        push: true
        force_tag: yes
        force_source: yes
      with_items:
        - "{{ clone_status.after }}"
        - latest  
      
    
    - name: "Build - Deleting Local Image From Build Server"
      when: clone_status.changed == true
      docker_image:
        state: absent
        name: "{{ image_name }}"
        tag: "{{ item }}"
      with_items:
        - "{{ clone_status.after }}"
        - latest
    
        
    - name: "Build - Logout to Docker-hub Account"
      when: clone_status.changed == true
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
        state: absent
       
    

- name: "Running Image On The Test Server"
  hosts: test
  become: true
  vars:
    image_name: "fujikomalan/oncompute"
    packages:
      - docker
      - pip
  tasks:
    

    - name: "Test - Installing Packages"
      yum:
        name: "{{ packages }}"
        state: present
    
    - name: "Test - Adding Ec2-user to docker group"
      user:
        name: "ec2-user"
        groups:
          - docker
        append: true
            
            
    - name: "Test - Installing Python Extension For Docker"
      pip:
        name: docker-py
            
            
    - name: "Test - Docker service restart/enable"
      service:
        name: docker
        state: started
        enabled: true
    
    
    - name: "Test - Pulling Docker Image"
      docker_image:
        name: "{{ image_name }}"
        source: pull
        force_source: true
      register: image_status      
    
    - name: "Test- Run Container"
      when: image_status.changed == true     
      docker_container:
        name: flaskapp
        image: "{{ image_name }}:latest"
        recreate: yes
        pull: yes
        published_ports:
          - "80:5000"
